name: CI

on:
  push:
    branches:
      - main

env:
  LatestCommitMessage: $(git log --format=%B -n 1 ${{ github.sha }})

jobs:
  check-changed-files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: check-changed-files
    outputs:
      shouldDeployWeb: ${{steps.changed-files-yaml.outputs.web_any_changed}}
      shouldDeployServer: ${{steps.changed-files-yaml.outputs.server_any_changed}}
      shouldDeployAll: ${{steps.changed-files-yaml.outputs.action_any_changed}}
      webChangedFiles: ${{steps.changed-files-yaml.outputs.web_all_changed_and_modified_files}}
      serverChangedFiles: ${{steps.changed-files-yaml.outputs.server_all_changed_and_modified_files}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            action:
              - '.github/workflows/**'
            server:
              - server/**
            web:
              - ./**
              - '!.github/**'
              - '!server/**'

  deploy-web:
    name: deploy-web
    needs: check-changed-files
    if: ${{ (needs.check-changed-files.outputs.shouldDeployWeb == 'true') || (needs.check-changed-files.outputs.shouldDeployAll == 'true') }}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: View Changed Web Files Name
        if: ${{ needs.check-changed-files.outputs.shouldDeployWeb == 'true' }}
        run: |
          echo "List all the web files that have changed: ${{ needs.check-changed-files.outputs.webChangedFiles }}"
          echo $LatestCommitMessage

  deploy-server:
    name: deploy-server
    needs: check-changed-files
    if: ${{ (needs.check-changed-files.outputs.shouldDeployServer == 'true') || (needs.check-changed-files.outputs.shouldDeployAll == 'true') }}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: View Changed Server Files Name
        if: ${{ needs.check-changed-files.outputs.shouldDeployServer == 'true' }}
        run: |
          echo "List all the server files that have changed: ${{ needs.check-changed-files.outputs.serverChangedFiles }}"
          echo $LatestCommitMessage
