name: CI

on:
  push:
    branches:
      - main

jobs:
  check-changed-files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: check-changed-files
    outputs:
      shouldDeployWeb: ${{steps.changed-files-yaml.outputs.web_any_changed}}
      shouldDeployServer: ${{steps.changed-files-yaml.outputs.server_any_changed}}
      shouldDeployAll: ${{steps.changed-files-yaml.outputs.action_any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            action:
              - '.github/workflows/**'
            server:
              - server/**
            web:
              - ./**
              - '!.github/**'
              - '!server/**'

      - name: View shouldDeployAll
        run: |
          echo "web_any_changed: ${{steps.changed-files-yaml.outputs.web_any_changed}}"
          echo "server_any_changed: ${{steps.changed-files-yaml.outputs.server_any_changed}}"
          echo "action_any_changed: ${{steps.changed-files-yaml.outputs.action_any_changed}}"

      - name: Run step if web file(s) change
        if: ${{steps.changed-files-yaml.outputs.web_any_changed == 'true'}}
        run: |
          echo "One or more web file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.web_added_files }}"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.web_all_changed_files }}"
          echo "List all the files that have modified: ${{ steps.changed-files-yaml.outputs.web_all_modified_files }}"
          echo "List all the files that have deleted: ${{ steps.changed-files-yaml.outputs.web_all_deleted_files }}"

      - name: Run step if server file(s) change
        if: ${{steps.changed-files-yaml.outputs.server_any_changed == 'true'}}
        run: |
          echo "One or more server file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.server_added_files }}"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.server_all_changed_files }}"
          echo "List all the files that have modified: ${{ steps.changed-files-yaml.outputs.server_all_modified_files }}"
          echo "List all the files that have deleted: ${{ steps.changed-files-yaml.outputs.server_all_deleted_files }}"

  view-shouldDeployAll:
    name: view-shouldDeployAll
    needs: check-changed-files
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: view shouldDeployAll values
        run: |
          echo ${{needs.check-changed-files.outputs.shouldDeployAll}}
          echo ${{needs.check-changed-files.outputs.shouldDeployWeb}} 
          echo ${{needs.check-changed-files.outputs.shouldDeployServer}}

  deploy-web:
    name: deploy-web
    needs: check-changed-files
    if: ${{needs.check-changed-files.outputs.shouldDeployWeb == 'true'}} || ${{needs.check-changed-files.outputs.shouldDeployAll == 'true'}}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: Get all test, doc and src files that have changed
        run: echo "your web files has changed,should deploy-web"

  deploy-server:
    name: deploy-server
    needs: check-changed-files
    if: ${{needs.check-changed-files.outputs.shouldDeployServer == 'true'}} || ${{needs.check-changed-files.outputs.shouldDeployAll == 'true'}}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: Get all test, doc and src files that have changed
        run: echo "your web files has changed,should deploy-server"
