name: CI

on:
  push:
    branches:
      - main

jobs:
  check-changed-files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: check-changed-files
    outputs:
      shouldDeployWeb: ${{steps.changed-files-yaml.outputs.web_any_changed}}
      shouldDeployServer: ${{steps.changed-files-yaml.outputs.server_any_changed}}
      shouldDeployAll: ${{steps.changed-files-yaml.outputs.action_any_changed}}
      fileChangeResult: ${{steps.changed-files-yaml.outputs}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            action:
              - '.github/workflows/**'
            server:
              - server/**
            web:
              - ./**
              - '!.github/**'
              - '!server/**'

  deploy-web:
    name: deploy-web
    needs: check-changed-files
    if: ${{ (needs.check-changed-files.outputs.shouldDeployWeb == 'true') || (needs.check-changed-files.outputs.shouldDeployAll == 'true') }}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: Get all test, doc and src files that have changed
        run: |
          echo "your web files has changed,should deploy-web"
          echo ${{needs.check-changed-files.outputs.fileChangeResult}}

  deploy-server:
    name: deploy-server
    needs: check-changed-files
    if: ${{ (needs.check-changed-files.outputs.shouldDeployServer == 'true') || (needs.check-changed-files.outputs.shouldDeployAll == 'true') }}
    runs-on: ubuntu-latest # windows-latest || macos-latest
    steps:
      - name: Get all test, doc and src files that have changed
        run: |
          echo "your web files has changed,should deploy-server"
          echo ${{needs.check-changed-files.outputs.fileChangeResult}}
