name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            server:
              - server/**
            web:
              - ./**
              - '!server/**'

      - name: Run step if web file(s) change
        if: steps.changed-files-yaml.outputs.web_any_changed == 'true'
        run: |
          echo "One or more web file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.web_added_files }}"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.web_all_changed_files }}"
          echo "List all the files that have modified: ${{ steps.changed-files-yaml.outputs.web_all_modified_files }}"
          echo "List all the files that have deleted: ${{ steps.changed-files-yaml.outputs.web_all_deleted_files }}"

      - name: Run step if server file(s) change
        if: steps.changed-files-yaml.outputs.server_any_changed == 'true'
        run: |
          echo "One or more server file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.server_added_files }}"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.server_all_changed_files }}"
          echo "List all the files that have modified: ${{ steps.changed-files-yaml.outputs.server_all_modified_files }}"
          echo "List all the files that have deleted: ${{ steps.changed-files-yaml.outputs.server_all_deleted_files }}"
